name: Build, Lint, and Test

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install Yarn dependencies
        run: yarn --immutable

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn --immutable --immutable-cache
      - run: |
          npm rebuild --verbose sharp
          yarn build
      - name: Cache snap build
        uses: actions/cache@v3
        with:
          path: ./packages/snap/dist
          key: snap-${{ runner.os }}-${{ github.sha }}
      - name: Cache site build
        if: github.ref == 'refs/heads/main'
        uses: actions/cache@v3
        with:
          path: ./packages/site/public
          key: site-${{ runner.os }}-${{ github.sha }}
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn --immutable --immutable-cache
      - run: yarn lint
      # - name: Validate RC changelog
      #   if: ${{ startsWith(github.head_ref, 'release/') }}
      #   run: yarn workspaces foreach --parallel --topological --verbose run auto-changelog validate --prettier --rc
      # - name: Validate changelog
      #   if: ${{ !startsWith(github.head_ref, 'release/') }}
      #   run: yarn workspaces foreach --parallel --topological --verbose run auto-changelog validate --prettier
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - prepare
      - build
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Restore snap build cache
        uses: actions/cache@v3
        with:
          path: ./packages/snap/dist
          key: snap-${{ runner.os }}-${{ github.sha }}
      - run: yarn install --immutable
      - name: Run tests
        run: yarn test
      - name: Require clean working directory
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "Working tree dirty at end of job"
            exit 1
          fi
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tests-artifacts-coverage
          path: packages/snap/coverage
